### ISSUE TITLE
sub-task of #3: Make use of JPA to get data from the database in the same network

### ISSUE THREAD

**Issue by rxue** [rxue/REST-API#9]

**Comment by rxue** [comment]
When making an @Embeddable class as composite primary key on the TimeSeries, the following error encountered:

    security-search-engine    | 10:19:20,108 INFO  [org.hibernate.envers.boot.internal.EnversServiceImpl] (ServerService Thread Pool -- 79) Envers integration enabled? : true
    security-search-engine    | 10:19:20,363 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 79) HHH000038: Composite-id class does not override equals(): rx.jpaentity.TimeSeriesId
    security-search-engine    | 10:19:20,363 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 79) HHH000039: Composite-id class does not override hashCode(): rx.jpaentity.TimeSeriesId
    security-search-engine    | 10:19:20,364 ERROR [org.jboss.msc.service.fail] (ServerService Thread Pool -- 79) MSC000001: Failed to start service jboss.persistenceunit."    security-search-engine-1.0-SNAPSHOT.war#primary": org.jboss.msc.service.StartException in service jboss.persistenceunit."    security-search-engine-1.0-SNAPSHOT.war#primary": javax.persistence.PersistenceException: [PersistenceUnit: primary] Unable to build Hibernate SessionFactory
    security-search-engine    | 	at org.jboss.as.jpa@24.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:198)
    security-search-engine    | 	at org.jboss.as.jpa@24.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:128)
    security-search-engine    | 	at java.base/java.security.AccessController.doPrivileged(Native Method)
    security-search-engine    | 	at org.wildfly.security.elytron-base@1.16.0.Final//org.wildfly.security.manager.WildFlySecurityManager.doChecked(WildFlySecurityManager.java:664)
    security-search-engine    | 	at org.jboss.as.jpa@24.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1.run(PersistenceUnitServiceImpl.java:213)
    security-search-engine    | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.ContextClassLoaderSavingRunnable.run(ContextClassLoaderSavingRunnable.java:35)
    security-search-engine    | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor.safeRun(EnhancedQueueExecutor.java:1990)
    security-search-engine    | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.doRunTask(EnhancedQueueExecutor.java:1486)
    security-search-engine    | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.EnhancedQueueExecutor$ThreadBody.run(EnhancedQueueExecutor.java:1377)
    security-search-engine    | 	at java.base/java.lang.Thread.run(Thread.java:834)
    security-search-engine    | 	at org.jboss.threads@2.4.0.Final//org.jboss.threads.JBossThread.run(JBossThread.java:513)
    security-search-engine    | Caused by: javax.persistence.PersistenceException: [PersistenceUnit: primary] Unable to build Hibernate SessionFactory
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.persistenceException(EntityManagerFactoryBuilderImpl.java:1327)
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1253)
    security-search-engine    | 	at org.hibernate.jipijapa-hibernate5-3@24.0.0.Final//org.jboss.as.jpa.hibernate5.TwoPhaseBootstrapImpl.build(TwoPhaseBootstrapImpl.java:44)
    security-search-engine    | 	at org.jboss.as.jpa@24.0.0.Final//org.jboss.as.jpa.service.PersistenceUnitServiceImpl$1$1.run(PersistenceUnitServiceImpl.java:170)
    security-search-engine    | 	... 10 more
    security-search-engine    | Caused by: org.hibernate.MappingException: Composite-id class must implement Serializable: rx.jpaentity.TimeSeriesId
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.mapping.RootClass.checkCompositeIdentifier(RootClass.java:293)
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.mapping.RootClass.validate(RootClass.java:276)
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.boot.internal.MetadataImpl.validate(MetadataImpl.java:347)
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.boot.internal.SessionFactoryBuilderImpl.build(SessionFactoryBuilderImpl.java:466)
    security-search-engine    | 	at org.hibernate@5.3.20.Final//org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:1250)
    security-search-engine    | 	... 12 more

Obviously the error cause: `Caused by: org.hibernate.MappingException: Composite-id class must implement Serializable: rx.jpaentity.TimeSeriesId` can be resolved by making `TimeSeriesId implements Serializable`

**Comment by rxue** [comment]
The following warning is way better to be removed:

    security-search-engine    | 10:46:45,999 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 79) HHH000038: Composite-id class does not override equals(): rx.jpaentity.TimeSeriesId
    security-search-engine    | 10:46:46,000 WARN  [org.hibernate.mapping.RootClass] (ServerService Thread Pool -- 79) HHH000039: Composite-id class does not override hashCode(): rx.jpaentity.TimeSeriesId
